security_default_confined = 0
security_driver = "none"

# change username and group to yours
user = "manuel"
group = "kvm"

cgroup_device_acl = [
    "/dev/null", "/dev/full", "/dev/zero",
    "/dev/random", "/dev/urandom",
    "/dev/ptmx", "/dev/kvm",
    "/dev/userfaultfd",
    "/dev/input/by-path/platform-i8042-serio-0-event-kbd"
]
